task: detection

num_classes: 7
remap_aircraft_category: True

train_dataloader: 
  type: DataLoader
  dataset: 
    type: AircraftDetection
    img_folder: data/SAR-AIRcraft-1.0/train/
    ann_file: data/SAR-AIRcraft-1.0/annotations/train.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 8
  num_workers: 4
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: AircraftDetection
    img_folder: data/SAR-AIRcraft-1.0/val/
    ann_file: data/SAR-AIRcraft-1.0/annotations/val.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 8
  num_workers: 4
  drop_last: False